/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef HAVE_BACKTRACE

#undef HAVE_CLOSE_RANGE

#undef HAVE_COPY_FILE_RANGE

#define HAVE_FALLOCATE

#define HAVE_FDATASYNC

#define HAVE_FORK

#undef HAVE_FSPACECTL

#define HAVE_FSTATAT

#undef HAVE_ICONV

#define HAVE_LINUX_LIMITS_H

#define HAVE_LISTMOUNT

#undef HAVE_NEW_MOUNT_API

#define HAVE_OPENAT

#define HAVE_PIPE2

#define HAVE_POSIX_FALLOCATE

#define HAVE_PTHREAD_SETNAME_NP

#define HAVE_READLINKAT

#define HAVE_SETXATTR

#define HAVE_SPLICE

#undef HAVE_STATX

#define HAVE_STRUCT_STAT_ST_ATIM

#undef HAVE_STRUCT_STAT_ST_ATIMESPEC

#define HAVE_SYS_XATTR_H

#define HAVE_UTIMENSAT

#define HAVE_VMSPLICE

#define PACKAGE_VERSION "3.19.0-rc0"

#undef USDT_ENABLED

