name: Build vMeer Engine Modular
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Baris di bawah ini otomatis menangani lisensi Android SDK
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build vMeer AAR
        # Kita gunakan --no-daemon agar lebih stabil di CI
        run: |
          chmod +x gradlew
          ./gradlew :vmeer-module:assembleRelease --no-daemon

      - name: Upload AAR Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: vmeer-engine-modular
          path: vmeer-module/build/outputs/aar/vmeer-module-release.aar
